# Dependabot version updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    versioning-strategy: increase
    commit-message:
      prefix: deps(npm)
    labels:
      - dependencies
      - npm

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(rust)
    labels:
      - dependencies
      - rust

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(ci)
    labels:
      - dependencies
      - github-actions

  # Docker (Dockerfile)
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    commit-message:
      prefix: deps(docker)
    labels:
      - dependencies
      - docker
